### ISSUE TITLE
 '@types/react-feature-flags@*' is not in the npm registry.

### ISSUE THREAD

**Issue by greg59650** [romaindso/react-feature-flags#39]
I tried installing React-feature-flags on my project.

After following the installation procedure:  `npm install --save react-feature-flags`

I find myself with the following problem :

`TS7016: Could not find a declaration file for module 'react-feature-flags'. '.../node_modules/react-feature-flags/dist/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/react-feature-flags` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-feature-flags';``

so i tried to install : `npm install --save-dev @types/react-feature-flags`  but I end up with the following error :

```
Not Found - GET https://registry.npmjs.org/@types%2freact-feature-flags - Not found
'@types/react-feature-flags@*' is not in the npm registry.
```

is there a solution for this problem ?

**Comment by romaindso** [comment]
Hi, 
The project is not written with Typescript but with plain Javascript, that's why you've got an implicit any type when using it in a TS project. 

Migrating on TS is on my todo list but in the meantime, you can unblock yourself by adding a declaration file 
Check this post, section "Plan C: Create a declaration file" 
https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3
